name: Build NodeJS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.17.1

    # 清除 npm 缓存
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      working-directory: nodejs
      run: npm i

    # 检查 lodash 是否安装成功
    - name: Check lodash installation
      working-directory: nodejs
      continue-on-error: true # 即使检查失败，也继续执行后续步骤
      run: |
        if ! node -e "require('lodash')" &> /dev/null; then
          echo "lodash is missing. Reinstalling..."
          npm install lodash
        else
          echo "lodash is installed."
        fi

    # 检查 qs 是否安装成功
    - name: Check qs installation
      working-directory: nodejs
      continue-on-error: true
      run: |
        if ! node -e "require('qs')" &> /dev/null; then
          echo "qs is missing. Reinstalling..."
          npm install qs
        else
          echo "qs is installed."
        fi

    # 检查关键文件是否存在
    - name: Check files existence
      working-directory: nodejs
      run: |
        if [ ! -f "src/util/ali.js" ]; then
          echo "File src/util/ali.js not found."
          exit 1
        fi
        if [ ! -f "src/util/quark.js" ]; then
          echo "File src/util/quark.js not found."
          exit 1
        fi
        if [ ! -f "src/spider/spider.js" ]; then
          echo "File src/spider/spider.js not found."
          exit 1
        fi

    - name: Run npm build
      working-directory: nodejs
      run: npm run build

    - name: Check dist/index.js existence
      working-directory: nodejs
      run: |
        if [ ! -f "dist/index.js" ]; then
          echo "dist/index.js not generated. Building might have failed."
          exit 1
        fi

    - name: Archive dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          nodejs/dist
